stages:
  - prepare
  - build

create-child-ci:
  stage: prepare
  image: alpine
  script:
    - apk add py3-jinja2
    - ./create-child-ci.py
  tags:
    - ci-build
    - x86_64
  artifacts:
    paths:
      - out
  only:
    - triggers
    - web
    - schedules

build:
  stage: build
  trigger:
    include:
      - artifact: out/child.yml
        job: create-child-ci
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  only:
    - triggers
    - web
    - schedules

