#!/bin/sh

set -e

## debug
if [ "$DOCKER_ABUILD_DEBUG" = "true" ]; then
  set -x
  PS4='$LINENO: '
fi

if [ "${PWD%aports/*}" = "$PWD" ]; then
  echo "Error: expecting to be run from within an aports/ tree!"
  echo "Could not find 'aports/' in the current path ($PWD)"
  exit 1
fi

DOCKER_VOLUMES="
    -v $PWD:/cwd
    -v ${HOME}/.abuild:/home/builder/.abuild
    -v ${HOME}/.abuild/.cache:/var/cache/apk
    -v ${HOME}/.abuild/.distfiles:/var/cache/distfiles
    -v ${PWD%aports/*}aports:/home/builder/aports
    -v ${PWD%aports/*}packages:/home/builder/packages
"

DOCKER="docker run -ti $DOCKER_VOLUMES -e DOCKER_ABUILD_DEBUG mor1/abuild"
$DOCKER "$@"
