#!/bin/sh

set -e

## debug
if [ "$DOCKER_ABUILD_DEBUG" = "true" ]; then
  set -x
  PS4='$LINENO: '
fi

if [ "${PWD%*/aports*}" = "$PWD" ]; then
  echo "Error: expecting to be run from within an aports tree!"
  echo "Could not find '/aports' in the current path ($PWD)"
  exit 1
fi

# use branch to figure out most appropriate alpine version
if [ -z "$DOCKER_ABUILD_VERSION" ]; then
  ABUILD_BRANCH=$(git status | head -1)
  ABUILD_BRANCH="${ABUILD_BRANCH##*[ /]}"
  ABUILD_BRANCH="${ABUILD_BRANCH%-stable}"

  case $ABUILD_BRANCH in
    [[:digit:]].[[:digit:]] )
      ALPINE_VERSION=$ABUILD_BRANCH
      ;;
    * )
      ALPINE_VERSION=edge
      ;;
  esac
else
  ALPINE_VERSION=$DOCKER_ABUILD_VERSION
fi

ABUILD_VOLUMES="
    -v ${HOME}/.abuild:/home/builder/.abuild
    -v ${PWD%/aports*}/aports:/home/builder/aports
"
for v in %%ALPINE_VOLUMES%%; do
  ABUILD_VOLUMES="$ABUILD_VOLUMES -v alpine-$ALPINE_VERSION-$v:/$v"
done

ABUILD_WORKDIR=/home/builder/aports${PWD#*/aports}
DOCKER="docker run -ti $ABUILD_VOLUMES -e DOCKER_ABUILD_DEBUG $DOCKER_ABUILD_ARGS"
$DOCKER --workdir $ABUILD_WORKDIR mor1/abuild:$ALPINE_VERSION "$@"
