stages:
  - build
  - publish
  - manifest

.build:
  stage: build
  image:
    name: registry.alpinelinux.org/alpine/infra/docker/exec/docker-image:latest
    pull_policy: always
  script: [pwd]
    
.publish:
  stage: publish
  image:
    name: registry.alpinelinux.org/alpine/infra/docker/exec/docker-image:latest
    pull_policy: always
  script: [pwd]

{% for branch in data %}
build-{{branch.rel_branch}}:
  extends: .build
  parallel:
    matrix:
      - ARCH:
      {% for arch in branch.arches %}
        - {{arch}}
      {% endfor %}
  tags:
    - ci-docker-image
    - $ARCH
  variables:
    EXEC_COMMAND: build
    SUBDIR: out/{{branch.rel_branch}}
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: create-child-ci

publish-{{branch.rel_branch}}:
  extends: .publish
  parallel:
    matrix:
      - ARCH:
      {% for arch in branch.arches %}
        - {{arch}}
      {% endfor %}
  tags:
    - ci-docker-image 
    - $ARCH
  variables:
    EXEC_COMMAND: publish
    DOCKER_TAG: "{{branch.rel_branch|trim('v')}}"

manifest-{{branch.rel_branch}}:
  stage: manifest
  image:
    name: registry.alpinelinux.org/alpine/infra/docker/exec/docker-image:latest
    pull_policy: always
  script: [pwd]
  variables:
    EXEC_COMMAND: manifest
    MANIFEST_ARCHES: {% for arch in branch.arches %}{{arch}} {% endfor +%}
    DOCKER_TAG: "{{branch.rel_branch|trim('v')}}"
  tags:
    - ci-docker-image
    - x86_64

{% endfor %}
