#!/bin/sh

readonly cmd=$1

manage_config() {
	docker run --user 1000:1000 --rm -it --workdir /mnt/abuild \
		-v dabuild-config:/mnt/abuild alpine sh
}

list_volumes() {
	docker volume ls --quiet --filter name="^dabuild"
}

usage() {
	cat <<- EOF
	dabuild: version (unknown)

	Available commands:
	  config: access abuild configuration
	  volumes: list created dabuild volumes
	  help: this help screen
	EOF
}


case $cmd in
	config) manage_config;;
	volumes) list_volumes;;
	help) usage;;
	*) usage; exit 1;;
esac
