FROM alpine:{{tag}}

RUN rm /etc/apk/repositories && \
    printf -- >> /etc/apk/repositories \
      'http://dl-cdn.alpinelinux.org/alpine/{{release}}/%s\n' \
      main community $(test edge = "{{release}}" && echo testing) && \
    printf -- >> /etc/apk/repositories \
      '/home/builder/packages/%s\n' \
      main community testing

RUN apk add --update-cache \
      alpine-conf \
      alpine-sdk \
      sudo \
      ccache \
    && apk upgrade -a \
    && setup-apkcache /var/cache/apk

RUN adduser -D builder \
    && addgroup builder abuild \
    && echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER builder
WORKDIR /home/builder
COPY entrypoint.sh /home/builder
RUN mkdir packages

ENTRYPOINT ["/home/builder/entrypoint.sh"]
