FROM alpine:%%ALPINE_TAG%%
MAINTAINER Richard Mortier <mort@cantab.net>

RUN apk add --update-cache \
      alpine-conf \
      alpine-sdk \
    && setup-apkcache /var/cache/apk

RUN rm /etc/apk/repositories && setup-apkrepos -1 \
    && printf -- '/home/builder/packages/%s\n' main community testing \
    >> /etc/apk/repositories \
    && sed -i 's!^#\(.*/testing\)$!\1!' /etc/apk/repositories \
    && apk update

RUN adduser -D builder \
    && addgroup builder abuild \
    && echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER builder
WORKDIR /home/builder
COPY entrypoint.sh /home/builder
RUN mkdir packages

ENTRYPOINT ["/home/builder/entrypoint.sh"]
